--En tant que SYS :
CREATE DIRECTORY DIRTESTPROG AS '/u01/userhome/oracle/sgbd/AjoutProg';

GRANT READ,WRITE ON DIRECTORY DIRTESTPROG TO cb;
GRANT EXECUTE ON DIRECTORY DIRTESTPROG TO cb;
GRANT READ,WRITE ON DIRECTORY DIRTESTPROG TO cc1;
GRANT EXECUTE ON DIRECTORY DIRTESTPROG TO cc1;
GRANT READ,WRITE ON DIRECTORY DIRTESTPROG TO cc2;
GRANT EXECUTE ON DIRECTORY DIRTESTPROG TO cc2;
GRANT READ,WRITE ON DIRECTORY DIRTESTPROG TO cc3;
GRANT EXECUTE ON DIRECTORY DIRTESTPROG TO cc3;
GRANT READ,WRITE ON DIRECTORY DIRTESTPROG TO cc4;
GRANT EXECUTE ON DIRECTORY DIRTESTPROG TO cc4;
GRANT READ,WRITE ON DIRECTORY DIRTESTPROG TO cc5;
GRANT EXECUTE ON DIRECTORY DIRTESTPROG TO cc5;
GRANT READ,WRITE ON DIRECTORY DIRTESTPROG TO cc6;
GRANT EXECUTE ON DIRECTORY DIRTESTPROG TO cc6;
