--Executer en tant que sys
DROP DIRECTORY DIRXML;
CREATE DIRECTORY DIRXML AS '/u01/userhome/oracle/sgbd/XSD';

GRANT READ,WRITE ON DIRECTORY DIRXML TO cb;
GRANT EXECUTE ON DIRECTORY DIRXML TO cb;
GRANT READ,WRITE ON DIRECTORY DIRXML TO cc1;
GRANT EXECUTE ON DIRECTORY DIRXML TO cc1;
GRANT READ,WRITE ON DIRECTORY DIRXML TO cc2;
GRANT EXECUTE ON DIRECTORY DIRXML TO cc2;
GRANT READ,WRITE ON DIRECTORY DIRXML TO cc3;
GRANT EXECUTE ON DIRECTORY DIRXML TO cc3;
GRANT READ,WRITE ON DIRECTORY DIRXML TO cc4;
GRANT EXECUTE ON DIRECTORY DIRXML TO cc4;
GRANT READ,WRITE ON DIRECTORY DIRXML TO cc5;
GRANT EXECUTE ON DIRECTORY DIRXML TO cc5;
GRANT READ,WRITE ON DIRECTORY DIRXML TO cc6;
GRANT EXECUTE ON DIRECTORY DIRXML TO cc6;