DECLARE
  P_DIRECTORY VARCHAR2(200);
  P_FILE VARCHAR2(200);
BEGIN
  P_DIRECTORY := 'DIRTESTPROG';
  P_FILE := 'programmations.xml';

  PACKAGE_AJOUTPROG.AJOUTPROG(
    P_DIRECTORY => P_DIRECTORY,
    P_FILE => P_FILE
  );
rollback; 
END;
/

select * from PROGRAMMATIONS_VIEW;
delete from PROGRAMMATIONS;
commit;